version: '3.8'

services:
  db:
    image: postgres:15
    container_name: telegram-auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_auth
      POSTGRES_USER: telegram
      POSTGRES_PASSWORD: telegram
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: telegram-auth-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/telegram_auth
      - SPRING_DATASOURCE_USERNAME=telegram
      - SPRING_DATASOURCE_PASSWORD=telegram
volumes:
  pgdata:

