version: '3.8'

services:
  db:
    image: postgres:15
    container_name: telegram-auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: telegram_auth
      POSTGRES_USER: telegram
      POSTGRES_PASSWORD: telegram
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: telegram-auth-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/telegram_auth
      SPRING_DATASOURCE_USERNAME: telegram
      SPRING_DATASOURCE_PASSWORD: telegram
    depends_on:
      - db

volumes:
  pgdata:
