spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
  springdoc:
    api-docs:
      path: /api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui
      operations-sorter: method
      enabled: true
      config-url: /api-docs/swagger-config
  security:
    enabled: false

telegram:
  bot:
    token: 8120838392:AAHkDJsHU7qDU5vHE55NP1C4cvRQXWEhNv4
logging:
  level:
    org.telegram.auth.telegramauth: DEBUG
    org.springframework: INFO

#jwt:
#  secret: CyqdyuZNxE2KQPP3Nx6ufk9FPHhiGRugXHC/UA24kyqF/phbN7ov7oVeQkljYnHyhuvIBVz1Wddjkk/3A6dz7g==
